### ISSUE TITLE
No Git Clone?

### ISSUE THREAD

**Issue by justindra** [node-girls-australia/express-workshop-2#10]
Not sure if this is still to come or I'm not seeing it, but going from Step 0 to Step 1, there were no instructions to clone the repo. Just to Fork it? and then suddenly adding `package.json` file.

**Comment by dmison** [comment]
Hi @justindra 

For those using Cloud9 it happens when you create a workspace

For those using a local setup, those instructions are incomplete at this point, but will be in the "Download the workshop files" steps.  

I'll leave this open until I add that material.  Thanks for the feedback

**Comment by dmison** [comment]
I've created "local setup" instructions as an option for those who don't want to go the cloud9 route but I avoided the use of git there in favour of just download the zip.  trying to minimize the number of different things people have to install & wrap their minds around

I might add a sidenote to that mentioning that if you already have git installed etc it is preferable to clone the repo.

**Comment by dmison** [comment]
I've added this to the local-setup "download the files" section.  Disclaimer of "if you have git installed we assume you know what you are doing" rather than detailed steps.
