### ISSUE TITLE
Quotes consistencies

### ISSUE THREAD

**Issue by justindra** [node-girls-australia/express-workshop-2#11]
In step 4, some parts of the code uses `"` (double quotes) to encapsulates strings and some places use `'` (single quotes). Would probably be good to decide on one or the other and keep it all consistent.

**Comment by justindra** [comment]
Also as a sidenote, the click to hide and show soluton arrows I feel like are the other way around?

**Comment by dmison** [comment]
Single quotes have snuck in as I've rewritten stuff I think.  Thanks for pointing it out.

Re the arrows, I see your point.  I think I meant them to indicate the current state, like up or down, rather than the action to take.  thinking about it some more.

**Comment by dmison** [comment]
@cheloya cleaned up all the quotes.  Thanks.  :-)

We went with single quotes for consistency with the NodeJS docs.  

Also console.log uses single quotes for strings as well so that might be nice to avoid any confusion that may arise.

**Comment by dmison** [comment]
raised specific issue for "solutions" button
