### ISSUE TITLE
Later: Should we also mention that we have talks about certains concepts covered

### ISSUE THREAD

**Issue by anchat1990** [node-girls-australia/express-workshop-2#7]
in the actual workshop?

**Comment by dmison** [comment]
I'd be leaning towards no ... it is something we should point out to attendees though.  

Maybe a printed list of the days agenda for each attendee with the talks etc on  it.  Approximate times etc.

**Comment by anchat1990** [comment]
thats a cool idea. will add that to my event day TODO list.
